// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface ActionTrace<T> {
    type:   string;
    req_id: string;
    data:   ActionTraceData<T>;
}

export interface ActionTraceData<T> {
    trx_id: string;
    idx:    number;
    depth:  number;
    trace:  Trace<T>;
}

export interface Trace<T> {
    receipt:         Receipt;
    act:             Act<T>;
    elapsed:         number;
    cpu_usage:       number;
    console:         string;
    total_cpu_usage: number;
    trx_id:          string;
    inline_traces:   any[];
}

export interface Act<T> {
    account:       string;
    name:          string;
    authorization: Authorization[];
    data:          T;
    hex_data:      string;
}

export interface Authorization {
    actor:      string;
    permission: string;
}

export interface Receipt {
    receiver:        string;
    act_digest:      string;
    global_sequence: number;
    recv_sequence:   number;
    auth_sequence:   Array<Array<number | string>>;
    code_sequence:   number;
    abi_sequence:    number;
}
