// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface ActionTrace {
    type:   string;
    req_id: string;
    data:   ActionTraceData;
}

export interface ActionTraceData {
    trx_id: string;
    idx:    number;
    depth:  number;
    trace:  Trace;
}

export interface Trace {
    receipt:         Receipt;
    act:             Act;
    elapsed:         number;
    cpu_usage:       number;
    console:         string;
    total_cpu_usage: number;
    trx_id:          string;
    inline_traces:   any[];
}

export interface Act {
    account:       string;
    name:          string;
    authorization: Authorization[];
    data:          ActData;
    hex_data:      string;
}

export interface Authorization {
    actor:      string;
    permission: string;
}

export interface ActData {
    from:     string;
    to:       string;
    quantity: string;
    memo:     string;
}

export interface Receipt {
    receiver:        string;
    act_digest:      string;
    global_sequence: number;
    recv_sequence:   number;
    auth_sequence:   Array<Array<number | string>>;
    code_sequence:   number;
    abi_sequence:    number;
}
