// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface TableDelta<T> {
    type:   string;
    req_id: string;
    data:   Data<T>;
}

export interface Data<T> {
    block_num: number;
    op:        string;
    key:       string;
    row:       T;
}
