// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Transfer {
    from:     string;
    to:       string;
    quantity: string;
    memo:     string;
}
